import { Lesson, LessonStep } from '../types/lesson';

// Try to import pre-fetched lessons from JSON (generated by fetch_wikihow.py)
let prefetchedLessons: Partial<Lesson>[] | null = null;

async function loadPrefetchedLessons(): Promise<Partial<Lesson>[]> {
    if (prefetchedLessons) return prefetchedLessons;
    try {
        const mod = await import('../data/wikihow_lessons.json');
        prefetchedLessons = mod.default || mod;
        return prefetchedLessons!;
    } catch {
        console.log('No pre-fetched wikiHow lessons found. Using AI generation fallback.');
        return [];
    }
}

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY || '';

interface WikiHowTopic {
    title: string;
    category: string;
    sourceUrl: string;
}

/**
 * Curated fallback topics (used if no JSON file exists).
 */
const WIKIHOW_TOPICS: WikiHowTopic[] = [
    // Technology
    { title: 'Компьютерийн нууц үгийг хэрхэн хүчтэй болгох вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Create-a-Strong-Password' },
    { title: 'Wi-Fi сүлжээнд хэрхэн холбогдох вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Connect-to-WiFi' },
    { title: 'Gmail хаяг хэрхэн нээх вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Create-a-Gmail-Account' },
    { title: 'Фэйсбүүк хаягаа хэрхэн хамгаалах вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Secure-Your-Facebook-Account' },
    { title: 'Скриншот хэрхэн авах вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Take-a-Screenshot' },
    { title: 'VPN гэж юу вэ, хэрхэн ашиглах вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Use-a-VPN' },
    { title: 'PDF файл хэрхэн үүсгэх вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Create-a-PDF' },
    { title: 'Утасны санах ойг хэрхэн чөлөөлөх вэ', category: 'Technology', sourceUrl: 'https://www.wikihow.com/Free-Up-Space-on-Your-Phone' },

    // Cooking
    { title: 'Өндөгийг хэрхэн зөв чанах вэ', category: 'Cooking', sourceUrl: 'https://www.wikihow.com/Boil-an-Egg' },
    { title: 'Гэртээ пицца хэрхэн хийх вэ', category: 'Cooking', sourceUrl: 'https://www.wikihow.com/Make-Pizza' },
    { title: 'Будаа хэрхэн зөв чанах вэ', category: 'Cooking', sourceUrl: 'https://www.wikihow.com/Cook-Rice' },
    { title: 'Банштай шөл хэрхэн хийх вэ', category: 'Cooking', sourceUrl: 'https://www.wikihow.com/Make-Dumplings' },
    { title: 'Хуурга хэрхэн хийх вэ', category: 'Cooking', sourceUrl: 'https://www.wikihow.com/Stir-Fry' },

    // Lifestyle
    { title: 'Өглөө эрт босох зуршлыг хэрхэн тогтоох вэ', category: 'Lifestyle', sourceUrl: 'https://www.wikihow.com/Wake-Up-Early' },
    { title: 'Стрессийг хэрхэн бууруулах вэ', category: 'Lifestyle', sourceUrl: 'https://www.wikihow.com/Reduce-Stress' },
    { title: 'Гэрээ хэрхэн цэвэрхэн байлгах вэ', category: 'Lifestyle', sourceUrl: 'https://www.wikihow.com/Keep-Your-House-Clean' },
    { title: 'Цагийг хэрхэн зөв зохицуулах вэ', category: 'Lifestyle', sourceUrl: 'https://www.wikihow.com/Manage-Your-Time' },
    { title: 'Сайн унтах зуршлыг хэрхэн бий болгох вэ', category: 'Lifestyle', sourceUrl: 'https://www.wikihow.com/Sleep-Better' },

    // Education
    { title: 'Англи хэлний үгийн сангаа хэрхэн нэмэгдүүлэх вэ', category: 'Education', sourceUrl: 'https://www.wikihow.com/Improve-Your-Vocabulary' },
    { title: 'Шалгалтанд хэрхэн бэлдэх вэ', category: 'Education', sourceUrl: 'https://www.wikihow.com/Study-for-an-Exam' },
    { title: 'Эссэ хэрхэн бичих вэ', category: 'Education', sourceUrl: 'https://www.wikihow.com/Write-an-Essay' },
    { title: 'Ном уншиж дуусгах зуршлыг хэрхэн бий болгох вэ', category: 'Education', sourceUrl: 'https://www.wikihow.com/Read-More-Books' },

    // Health
    { title: 'Гэртээ дасгал хэрхэн хийх вэ', category: 'Health', sourceUrl: 'https://www.wikihow.com/Exercise-at-Home' },
    { title: 'Эрүүл хооллолтын зуршлыг хэрхэн бий болгох вэ', category: 'Health', sourceUrl: 'https://www.wikihow.com/Eat-Healthy' },
    { title: 'Ус хангалттай уух зуршлыг хэрхэн тогтоох вэ', category: 'Health', sourceUrl: 'https://www.wikihow.com/Drink-More-Water' },

    // Finance
    { title: 'Мөнгөө хэрхэн зөв хэмнэх вэ', category: 'Finance', sourceUrl: 'https://www.wikihow.com/Save-Money' },
    { title: 'Хувийн төсвийг хэрхэн төлөвлөх вэ', category: 'Finance', sourceUrl: 'https://www.wikihow.com/Make-a-Budget' },
];

/**
 * Uses Gemini AI to generate a full Mongolian lesson from a topic (fallback).
 */
const generateLessonFromTopic = async (topic: WikiHowTopic): Promise<Partial<Lesson> | null> => {
    if (!API_KEY) {
        return getMockWikiHowLesson(topic);
    }

    try {
        const { GoogleGenerativeAI } = await import('@google/generative-ai');
        const genAI = new GoogleGenerativeAI(API_KEY);
        const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

        const prompt = `
            You are an expert educator creating lessons inspired by wikiHow's step-by-step format.
            Create a detailed lesson in MONGOLIAN for: ${topic.title} (Category: ${topic.category})

            Return ONLY valid JSON:
            {"summary":"Brief Mongolian summary","steps":[{"title":"Step title","content":"Step content","tips":["Tip 1","Tip 2"]}],"tags":["tag1","tag2"]}
        `;

        const result = await model.generateContent(prompt);
        const text = result.response.text().replace(/```json/g, '').replace(/```/g, '').trim();
        const data = JSON.parse(text);

        const steps: LessonStep[] = data.steps.map((step: any, index: number) => ({
            id: `step-${index + 1}`,
            title: step.title,
            content: step.content,
            tips: step.tips
        }));

        return {
            title: topic.title,
            category: topic.category,
            summary: data.summary,
            author: 'WikiHow / AI',
            steps,
            tags: data.tags || [topic.category.toLowerCase()],
            isPaid: false,
            sourceUrl: topic.sourceUrl,
        };
    } catch (error) {
        console.error(`Error generating lesson for "${topic.title}":`, error);
        return getMockWikiHowLesson(topic);
    }
};

const getMockWikiHowLesson = (topic: WikiHowTopic): Partial<Lesson> => ({
    title: topic.title,
    category: topic.category,
    summary: `${topic.title} - энэ хичээлээр та алхам алхмаар суралцах болно.`,
    author: 'WikiHow / AI',
    steps: [
        { id: 'step-1', title: 'Бэлтгэл', content: 'Эхлээд шаардлагатай зүйлсээ бэлтгэнэ.', tips: ['Тайван байх', 'Бэлтгэлтэй байх'] },
        { id: 'step-2', title: 'Үндсэн алхам', content: 'Зааврын дагуу үйлдлээ гүйцэтгэнэ.', tips: ['Анхааралтай байх'] },
        { id: 'step-3', title: 'Дүгнэлт', content: 'Үр дүнгээ шалгаж, дахин давтана.', tips: ['Тогтмол давтах'] },
    ],
    tags: [topic.category.toLowerCase(), 'wikihow'],
    isPaid: false,
    sourceUrl: topic.sourceUrl,
});

/**
 * Generate WikiHow-style lessons.
 * First tries to load from pre-fetched JSON (from fetch_wikihow.py),
 * then falls back to AI generation.
 */
export const generateAllWikiHowLessons = async (
    onProgress?: (done: number, total: number, currentTitle: string) => void
): Promise<Partial<Lesson>[]> => {
    // Try pre-fetched JSON first
    const prefetched = await loadPrefetchedLessons();
    if (prefetched.length > 0) {
        console.log(`Loaded ${prefetched.length} pre-fetched wikiHow lessons from JSON`);
        onProgress?.(prefetched.length, prefetched.length, 'JSON файлаас ачааллаа!');
        return prefetched;
    }

    // Fallback: generate via AI
    console.log('No pre-fetched data, generating via AI...');
    const lessons: Partial<Lesson>[] = [];
    const total = WIKIHOW_TOPICS.length;

    for (let i = 0; i < total; i++) {
        const topic = WIKIHOW_TOPICS[i];
        onProgress?.(i, total, topic.title);

        const lesson = await generateLessonFromTopic(topic);
        if (lesson) {
            lessons.push(lesson);
        }

        if (API_KEY && i < total - 1) {
            await new Promise(resolve => setTimeout(resolve, 500));
        }
    }

    onProgress?.(total, total, 'Дууссан!');
    return lessons;
};

export const getWikiHowTopicCount = () => {
    // If prefetched data was loaded, return its count; else topics count
    if (prefetchedLessons && prefetchedLessons.length > 0) return prefetchedLessons.length;
    return WIKIHOW_TOPICS.length;
};
